artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://universe.roboflow.com/beyblade-djcpy/beyblade-dtd3d/dataset/14
  roboflow_api_key: r1etVuiNE3pRyNSKgAGM
  dataset_version: yolov11
  dataset_name: Beyblade-14

model_training:
  root_dir: artifacts/training
  weight_models_dir: artifacts/training/weights
  yaml_path: artifacts/data_ingestion/Beyblade-14/data.yaml
  weight_model: yolo11n.pt
  epochs: 100
  patience: 25
  image_size: 640
  project_name: beyblade_detector-nano

arena_bounds_selector:
  root_dir: artifacts/arena_bounds_selector
  input_video_path: artifacts/input_video/beyblade_trim.mov
  window_name: Arena Bounds Selector

video_processor:
  root_dir: artifacts/video_processor
  input_video_path: artifacts/input_video/beyblade_trim.mov
  output_video_path: artifacts/video_processor/outputs
  arena_bounds: [100, 100, 500, 500]
  visualization: True

battle_analyzer:
  root_dir: artifacts/battle_analyzer
  movement_threshold: 0.5

beyblade_detector:
  root_dir: artifacts/beyblade_detector-nano
  model_path: artifacts/training/beyblade_detector-nano/weights/best.pt
  image_size: 640
  confidence_threshold: 0.5

battle_summary:
  root_dir: artifacts/battle_summary
